### ISSUE TITLE
Use Frontmatter Title to Allow Automatic Listings

### ISSUE THREAD

**Issue by hacdias** [ipfs/spec-generator#11]
Context: https://github.com/ipfs/specs/pull/385#discussion_r1157900557.

Currently, the specs files do not use the title in the frontmatter, but in the file itself, which does not happen with the remaining pages. This makes generating listings harder.

Proposal is to add `title` and `description` to the frontmatter of the specs. This will allow us to automatically generate the listings of the pages, instead of keeping them manually.

```
{%- for post in collections.all -%}
  <li>{{ post.data.title }}</li>
{%- endfor -%}
```

Then, we can add a `tag: ipip` to the IPIPs and iterate over `collections.ipips`.

**Comment by hacdias** [comment]
@lidel I think this is something we should _really_ do in terms of consistency and before https://github.com/ipfs/specs/pull/385.

**Comment by lidel** [comment]
Agree, we need this for https://github.com/ipfs/specs/pull/385.

@hacdias perhaps do `title` and `description` for now? `<meta name="description" (..)` will improve how specs are presented in search results  (https://developers.google.com/search/docs/appearance/snippet).
