### ISSUE TITLE
Meaningful description in search results

### ISSUE THREAD

**Issue by lidel** [ipfs/spec-generator#14]
Now that we added `description` in https://github.com/ipfs/specs/pull/408 we should use it to add meaningful header for SEO (https://developers.google.com/search/docs/appearance/snippet):

```html
<meta name="description" content="TODO">
```

@hacdias mind adding while we are at this? :pray:

**Comment by hacdias** [comment]
Eg 
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/5447088/236873640-d5c151a3-7e75-4881-820c-371bfe3c7db5.png">

**Comment by lidel** [comment]
Ah, yes, I looked at cached HTML, my bad :sweat_smile:
