### ISSUE TITLE
Move to ipfs org

### ISSUE THREAD

**Issue by lidel** [ipfs/spec-generator#2]
Since we are committed to use this in https://github.com/ipfs/specs/pull/382 for https://specs.ipfs.tech/, 
we would like to move this repo to https://github.com/ipfs/ org to reduce friction around maintenance (reuse permission model present in the org, set up automatic publishing to NPM etc).

@darobin would the move be ok? 
(if so, please grant me admin in this repo or transfer it to https://github.com/ipfs/ youself :pray:)

**Comment by darobin** [comment]
Of course! Moving this was always the plan, I only started this here to avoid clutter there while it was a baby. Moving now.
